add fix note

diff --git a/.github/workflows/init.yml b/.github/workflows/init.yml
--- a/.github/workflows/init.yml
+++ b/.github/workflows/init.yml
@@ -58,27 +58,30 @@ jobs:
             echo "warn: Package path not found: $OLD_PACKAGE_PATH"
           fi
 
-          echo "info: Updating strings.xml..."
-          find . -type f -name "strings.xml" | while read STRING_FILE; do
-            if [[ -f "$STRING_FILE" ]]; then
-              ESCAPED_OLD_NAME=$(echo "$OLD_NAME" | sed -e 's/[&/\]/\\&/g')
-              ESCAPED_NEW_NAME=$(echo "$NEW_NAME" | sed -e 's/[&/\]/\\&/g')
-              ESCAPED_OLD_DETAILS=$(echo "$OLD_DETAILS" | sed -e 's/[&/\]/\\&/g')
-              ESCAPED_NEW_DETAILS=$(echo "$NEW_DETAILS" | sed -e 's/[&/\]/\\&/g')
-
-              sed -i -E "s|>${ESCAPED_OLD_NAME}<|>${ESCAPED_NEW_NAME}<|g" "$STRING_FILE"
-              sed -i -E "s|>${ESCAPED_OLD_DETAILS}<|>${ESCAPED_NEW_DETAILS}<|g" "$STRING_FILE"
-
-              echo "success: Updated $STRING_FILE"
-            else
-              echo "warn: strings.xml not found."
-            fi
-          done
-
       - name: Commit and push changes
         run: |
           git config --global user.name 'github-actions'
           git config --global user.email 'actions@github.com'
 
           git add .
-          git diff --quiet && echo "warn: No changes detected. Skipping commit." || (git commit -m "Updated project details from metadata" && git push)
+          git commit -m "Update Metadata" || echo "No changes to commit"
+          git push
+
+# Add this to the end of `Load metadata...` after fixing error in following code:
+
+# echo "info: Updating strings.xml..."
+# find . -type f -path "*/res/values/strings.xml" | while read STRING_FILE; do
+#   if [[ -f "$STRING_FILE" ]]; then
+#     ESCAPED_OLD_NAME=$(echo "$OLD_NAME" | sed -e 's/[\/&]/\\&/g' -e 's/"/\\"/g')
+#     ESCAPED_NEW_NAME=$(echo "$NEW_NAME" | sed -e 's/[\/&]/\\&/g' -e 's/"/\\"/g')
+#     ESCAPED_OLD_DETAILS=$(echo "$OLD_DETAILS" | sed -e 's/[\/&]/\\&/g' -e 's/"/\\"/g')
+#     ESCAPED_NEW_DETAILS=$(echo "$NEW_DETAILS" | sed -e 's/[\/&]/\\&/g' -e 's/"/\\"/g')
+
+#     sed -i -E "s|(<string[^>]*name=\"app_name\"[^>]*>)[^<]+|\1$ESCAPED_NEW_NAME|g" "$STRING_FILE"
+#     sed -i -E "s|(<string[^>]*name=\"app_details\"[^>]*>)[^<]+|\1$ESCAPED_NEW_DETAILS|g" "$STRING_FILE"
+
+#     echo "success: Updated $STRING_FILE"
+#   else
+#     echo "warn: strings.xml not found."
+#   fi
+# done
